
on:
  pull_request:
    branches: [dev]
    types:
      - closed
  workflow_dispatch:

jobs:
  Build:
    environment: Development
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true    
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_DOMAIN }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Publish image to Azure Registry
        run: |
          docker build --build-arg KC_DB_URL=${{ vars.KC_DB_URL }} KC_DB_USERNAME=${{ secrets.KC_DB_USERNAME }} KC_DB_PASSWORD=${{ secrets.KC_DB_PASSWORD }} KC_DB_SCHEMA=${{ vars.KC_DB_SCHEMA}} KC_PROXY=${{ vars.KC_PROXY }} KC_PROXY_ADDRESS_FORWARDING=${{ vars.KC_PROXY_ADDRESS_FORWARDING}} KC_HTTP_ENABLED=${{ vars.KC_HTTP_ENABLED }} KEYCLOAK_ADMIN=${{ secrets.KEYCLOAK_ADMIN }} KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }} KEYTOOL_PASSWORD=${{ secrets.KEYTOOL_PASSWORD}} -t ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }}
  Deploy:
    needs: Build
    environment: 
      name: Development
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_DOMAIN }}/${{ secrets.REGISTRY_REPO }}:${{ github.sha }}'



